services:
  keycloak:
    image: quay.io/keycloak/keycloak:25.0.0
    environment:
      - KEYCLOAK_ADMIN=admin
      - KEYCLOAK_ADMIN_PASSWORD=admin
    command: start-dev
    ports:
      - 8080:8080
  db:
    image: postgres:latest
    ports:
      - "5432:5432" 
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_DB: fwn-api_development
  minio:
    container_name: minio
    image: minio/minio:latest
    volumes:
      - "minio_data:/data"
    ports:
      - "9000:9000"
    networks:
      - minio_network
    restart: always      
    environment:
      MINIO_ROOT_USER: "admin"
      MINIO_ROOT_PASSWORD: "adminaaaaa"      
    command: server /data
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/live"]
      interval: 30s
      timeout: 20s
      retries: 3

networks:
  minio_network:
    driver: bridge
    
volumes:
  minio_data:
    driver: local